---
- name: Install PostgreSQL
  hosts: db
  become: true

  tasks:
    - name: Create the file repository configuration
      ansible.builtin.apt_repository:
        repo: deb-src http://apt.postgresql.org/pub/repos/apt focal-pgdg main
        state: present
        filename: /etc/apt/sources.list.d/pgdg.list
        update_cache: no
    - name: Import the repository signing key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present                
    - name: Install the latest version of PostgreSQL
      apt:
        name: postgresql
        update_cache: yes
        state: present
    - name: Update postgresql.conf file
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        line: "listen_addresses = '{{ internal_ip }}'"
      notify: Restart PostgreSQL
    - name: Update pg_hba.conf file
      lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        line: "host all postgres 0.0.0.0/0 md5"
      notify: Restart PostgreSQL
    - name: Update pg_hba.conf file
      lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        line: "host replication postgres 0.0.0.0/0 md5"
      notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      systemd: 
        name=postgresql
        state=restarted
